platform :ios, '8.0'
target 'lemonoa' do
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'GoogleMaps'
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
